url: http://docs.hpcloud.com/
markdown: md2html
exclude: [README.md, Makefile, stackato-one.yml, stackato-two.yml, jenkins]
include: [devplatform/stackato/images]
relative_permalinks: false

navigation: 
  main:
  - text: HP Helion Documentation
    url: /
  - text: HP Helion OpenStack
    url: /helion/openstack/ga
  - text: HP Helion OpenStack Community 
    url: /helion/community/
  - text: HP Helion Development Platform 
    url: /helion/devplatform/
  - text: HP Helion Public Cloud
    url: /pc-overview/
  - text: HP Cloud Service Automation
    url: /automation/
  - text: HP Cloud OS for Moonshot
    url: /cloudos/moonshot/
  - text: HP CloudSystem
    url: http://www.hp.com/go/cloudsystem/docs
  - text: HP Cloud OS (Deprecated)
    url: /cloudos/
  public-cloud:
  - text: HP Helion Public Cloud Documentation
    url: /pc-overview/
  - text: Available Services
    url: /services/
  - text: Language Bindings
    url: /bindings/
  - text: APIs
    url: /api/
  - text: CLIs
    url: /cli/
  - text: FAQ
    url: /faq/
  - text: Site Overview 
    url: /site-overview/
  - text: HP Helion Documentation
    url: / 
  mc:
  - text: Overview
    url: /mc/
  - text: Main Dashboard
    url: /mc/dashboard/
  - text: Console Pages Site Map
    url: /mc/sitemap/
  mc-compute:
  - text: Console Overview
    url: /mc/
  - text: Servers Screen
    url: /mc/compute/servers/
  - text: Images Screen
    url: /mc/compute/images/
  - text: Volumes Screen
    url: /mc/compute/volumes/
  - text: Network Screen
    url: /mc/compute/networks/
  - text: Security Groups Screen
    url: /mc/compute/security-groups/
  - text: Floating IPs Screen
    url: /mc/compute/floating-ips/
  - text: Key Pairs Screen
    url: /mc/compute/key-pairs/
  - text: Console Pages Site Map
    url: /mc/sitemap/
  mc-object-storage:
  - text: Console Overview
    url: /mc/
  - text: Object Storage Dashboard
    url: /mc/object-storage/
  - text: Use Cases
    url: /mc/object-storage/use-cases/
  unix-cli:
  - text: Site home page
    url: /
  - text: Overview
    url: /cli/unix/
  - text: Installation
    url: /cli/unix/2/install/
  - text: Account Configuration
    url: /cli/unix/2/configuration/
  - text: Advanced Account Management
    url: /cli/unix/2/account-management/
  - text: Compute Examples
    url: /cli/unix/2/compute/
  - text: Object Storage Examples
    url: /cli/unix/2/object-storage/
  - text: CDN Examples
    url: /cli/unix/2/cdn/
  - text: Block Storage Examples
    url: /cli/unix/2/block-storage/
  - text: DNS Examples
    url: /cli/unix/2/dns/
  - text: CLI Reference
    url: /cli/unix/2/reference/
  - text: CLI for v12.12
    url: /cli/unix#1212
  - text: Release Notes
    url: /cli/unix/release-notes/
  win-cli:
  - text: Site home page
    url: /
  - text: Overview
    url: /cli/windows/
  - text: Installation
    url: /cli/windows/installation/
  - text: Non-Service Specific Commands
    url: /cli/windows/commands/
  - text: Compute Examples
    url: /cli/windows/compute/
  - text: Object Storage Examples
    url: /cli/windows/containers-and-folders/
  - text: Block Storage Examples
    url: /cli/windows/block-storage/
  - text: CLI Reference
    url: /cli/windows/reference/
  - text: Getting Help
    url: /cli/windows/help/
  - text: Release Notes
    url: /cli/windows/release-notes/
  win-2-cli:
  - text: Site home page
    url: /
  - text: Overview
    url: /cli/windows/2/
  - text: Installation
    url: /cli/windows/2/installation/
  - text: Non-Service Specific Commands
    url: /cli/windows/2/commands/
  - text: Compute Examples
    url: /cli/windows/2/compute/
  - text: Object Storage Examples
    url: /cli/windows/2/containers-and-folders/
  - text: Block Storage Examples
    url: /cli/windows/2/block-storage/
  - text: CLI Reference
    url: /cli/windows/2/reference/
  - text: Getting Help
    url: /cli/windows/2/help/
  - text: Release Notes
    url: /cli/windows/2/release-notes/
  nova-cli:
  - text: Site home page
    url: /
  - text: Overview
    url: /cli/nova
  - text: Installation
    url: https://community.hpcloud.com/article/cloud-135-cli-installation-instructions
  fog:
  - text: Site home page
    url: /
  - text: Overview
    url: /bindings/fog/
  - text: Installation
    url: /bindings/fog/install/
  - text: Connecting to the Service
    url: /bindings/fog/connect/
  - text: Object Storage Examples
    url: /bindings/fog/object-storage/
  - text: Compute Examples
    url: /bindings/fog/compute/
  - text: CDN Examples
    url: /bindings/fog/cdn/
  - text: Block Storage Examples
    url: /bindings/fog/block-storage/
  - text: Release Notes
    url: /bindings/fog/release-notes/
  jclouds:
  - text: Site home page
    url: /
  - text: Overview
    url: /bindings/jclouds/
  - text: Compute Examples
    url: /bindings/jclouds/compute/
  - text: CDN Examples
    url: /bindings/jclouds/cdn/
  - text: Object Storage Examples
    url: /bindings/jclouds/object-storage/
  cloudos:
  - text: HP Cloud OS Home  (Deprecated)
    url: /cloudos/
  - text: Prepare
    url: /cloudos/prepare/  	
  - text: Install
    url: /cloudos/install/
  - text: Manage
    url: /cloudos/manage/
  - text: Develop
    url: /cloudos/develop/
  - text: Community Forum
    url: /cloudos/forum/		
  - text: OpenStack Links
    url: /cloudos/openstack/	
  - text: Site Index
    url: /cloudos/siteindex/
  - text: HP Helion Documentation
    url: /
  moonshot:
  - text: HP Cloud OS for Moonshot Home
    url: /cloudos/moonshot/
  - text: Prepare
    url: /cloudos/moonshot/prepare/  	
  - text: Install
    url: /cloudos/moonshot/install/
  - text: Manage
    url: /cloudos/moonshot/manage/
  - text: Develop
    url: /cloudos/moonshot/develop/
  - text: Community Forum
    url: /cloudos/moonshot/community/		
  - text: Related Topics
    url: /cloudos/moonshot/related-topics/	
  - text: Site Index
    url: /cloudos/moonshot/siteindex/
  - text: HP Helion Documentation
    url: /
  community: 
  - text: HP Helion OpenStack Community Doc Home
    url: /helion/community/
  - text: Release Notes
    url: /helion/community/release-notes/  	
  - text: FAQ
    url: /helion/community/faq/ 		
  - text: Installation & Configuration
    url: /helion/community/install-overview/		
  - text: Related Documentation
    url: /helion/community/related-links/	
  - text: End User License Agreement
    url: /helion/community/eula/
  - text: Site Index
    url: /helion/community/siteindex/
  - text: HP Helion Documentation
    url: /
  commercial: 
  - text: HP Helion OpenStack Doc Home
    url: /helion/openstack/
  - text: Release Notes
    url: /helion/openstack/release-notes/ 
  - text: FAQ
    url: /helion/openstack/faq/  
  - text: Technical Overview
    url: /helion/openstack/technical-overview/ 
  - text: Services Overview
    url: /helion/openstack/services/overview/
  - text: Support Matrix
    url: /helion/openstack/support-matrix-beta/ 		
  - text: Installation & Configuration Overview
    url: /helion/openstack/install-beta-overview/	
  - text: Installation Prerequisites
    url: /helion/openstack/install-beta/prereqs/
  - text: Installation for KVM Hypervisor
    url: /helion/openstack/install-beta/kvm/
  - text: Installation for HP StoreVirtual VSA Support
    url: /helion/openstack/install-beta/vsa/		
  - text: Installation for ESX Hypervisor
    url: /helion/openstack/install-beta/esx/
  - text: OVSvApp Deployment for HP VCN on ESX hosts 
    url: /helion/openstack/install-beta/ovsvapp/
  - text: Installation for DNSaaS Support 
    url: /helion/openstack/install-beta/dnsaas/		
  - text: Related Documentation
    url: /helion/openstack/related-links/	
  - text: Glossary
    url: /helion/openstack/glossary/ 	
  - text: Preview Agreement
    url: /helion/openstack/eula/
  - text: Open Source and Third-Party Software License Agreements
    url: /helion/openstack/3rd-party-license-agreements/	
  - text: Site Index
    url: /helion/openstack/siteindex/
  - text: HP Helion Documentation
    url: / 
  commercial.ga: 
  - text: HP Helion OpenStack Doc Home
    url: /helion/openstack/ga/
  - text: Release Notes
    url: /helion/openstack/ga/release-notes/ 
  - text: FAQ
    url: /helion/openstack/ga/faq/  
  - text: Technical Overview
    url: /helion/openstack/ga/technical-overview/ 
  - text: Services Overview
    url: /helion/openstack/ga/services/overview/
  - text: Support Matrix
    url: /helion/openstack/ga/support-matrix/ 		
  - text: Installation & Configuration Overview
    url: /helion/openstack/ga/install/overview/	
  - text: Installation Prerequisites
    url: /helion/openstack/ga/install/prereqs/
  - text: Installation for KVM Hypervisor
    url: /helion/openstack/ga/install/kvm/
  - text: Installation for ESX Hypervisor
    url: /helion/openstack/ga/install/esx/
  - text: Back Up and Restore
    url: /helion/openstack/ga/backup.restore/
  - text: Related Documentation
    url: /helion/openstack/ga/related-links/	
  - text: Glossary
    url: /helion/openstack/ga/glossary/ 	
  - text: Preview Agreement
    url: /helion/openstack/ga/eula/
  - text: Open Source and Third-Party Software License Agreements
    url: /helion/openstack/ga/3rd-party-license-agreements/	
  - text: Site Index
    url: /helion/openstack/ga/siteindex/
  - text: HP Helion Documentation
    url: / 
  devplatform: 
  - text: HP Helion Development Platform Doc Home
    url: /helion/devplatform/
  - text: Development Platform Installation & Configuration
    url: /helion/devplatform/community/install-dev-platform/
  - text: Application Lifecycle Service Installation & Configuration
    url: /helion/devplatform/community/install-als/
  - text: ALS Documentation
    url: /als/v1/
  - text: Release Notes
    url: /helion/devplatform/community/release-notes/     
  - text: Related Documentation
    url: /helion/devplatform/community/related-topics/
  - text: HP Helion Documentation Home
    url: /
  apinavigation:
  - text: Site home page
    url: /
  - text: API Overview
    url: /api/
  - text: Identity Service
    url: /api/identity/
  - text: Object Storage
    url: /api/object-storage/
  - text: Compute Service
    url: /api/compute/
  - text: Block Storage
    url: /api/block-storage/
  - text: CDN
    url: /api/CDN/
  - text: RDB for MySQL
    url: /api/dbaas/
  - text: Load Balancer
    url: /api/lbaas/
  - text: DNS
    url: /api/dns/
  - text: Monitoring
    url: /api/monitoring/
  - text: ALS Documentation
    url: https://apaas-docs.hpcloud.com
  - text: Messaging
    url: /api/msgaas/
